-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 09:28:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------
DROP DATABASE IF EXISTS Restaurant;
CREATE DATABASE Restaurant;
USE Restaurant ;

-- -----------------------------------------------------
-- Table `Restaurant`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`Orders` (
  `Order_ID` INT NOT NULL,
  `Customer_ID` INT NULL,
  `Meals` VARCHAR(45) NULL,
  `Price` FLOAT(5) NULL,
  PRIMARY KEY (`Order_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`Entrees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`Entrees` (
  `Meals` VARCHAR(45) NOT NULL,
  `Entrees` VARCHAR(45) NULL,
  `Deserts` VARCHAR(45) NULL,
  `Sides` VARCHAR(45) NULL,
  `Price` FLOAT(5) NULL,
  PRIMARY KEY (`Meals`))
ENGINE = InnoDB;

CREATE TABLE Customers (
	Customer_ID INT,
    Customer_FNAME varchar(15),
    Customer_LNAME varchar(15),
    Phone_Num varchar(10),
    Address varchar(100),
    Email varchar(50),
    PRIMARY KEY(Customer_ID)
);

CREATE TABLE CHEF (
	Chef_ID INT,
    Chef_Name varchar(100),
    Chef_Salary INT
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
